In [14]:
import numpy as np
import matplotlib.pyplot as plt

In [50]:
import numpy as np

class perceptron:

    def __init__(self , learning_rate = 0.01 , n = 1000):
        self.lr = learning_rate
        self.n_iters =  n
        self.activation_function = self.unit_step_function
        self.weights = None
        self.bias = None


    def fit(self , X,y):
        n_sample , n_feature = X.shape


        #init weight
        self.weights = np.zeros(n_feature)
        self.bias = 0

        y_ =[]
        for i in y:
            if (i>0):
                y_.append(1)
            else:
                y_.append(-1)
        # y_ = np.array([1 if i>0 else 0 for i in y])

        for _ in range(self.n_iters):
            for idx, x_i in enumerate(X):
                linear_output = np.dot(x_i , self.weights) + self.bias
                y_predicted = self.activation_function(linear_output)

                update = self.lr* (y_[idx]- y_predicted)
                self.weights += update * x_i
                self.bias +=update


    def prediction(self , X):
        linear_output = np.dot(X , self.weights) + self.bias
        y_predicted = self.activation_function(linear_output)
        return y_predicted

    
    def unit_step_function(self , x):
         return np.where(x>=0 ,1, -1)



```
# This is formatted as code
```

# New Section

In [16]:
#print(Data)


In [17]:
import pandas as pd

def read_csv(filename):
  data = pd.read_csv(filename) #Please add four spaces here before this line
  return(np.array(data)) #Please add four spaces here before this line

Data1 = read_csv('/content/appendix - Sheet1.csv')

In [18]:
Data1

array([[1, '−0.6508', '0.1097', 4.0009, '−1.0000'],
       [2, '−1.4492', '0.8896', 4.4005, '−1.0000'],
       [3, '2.085', '0.6876', 12.071, '−1.0000'],
       [4, '0.2626', '1.1476', 7.7985, '1'],
       [5, '0.6418', '1.0234', 7.0427, '1'],
       [6, '0.2569', '0.673', 8.3265, '−1.0000'],
       [7, '1.1155', '0.6043', 7.4446, '1'],
       [8, '0.0914', '0.3399', 7.0677, '−1.0000'],
       [9, '0.0121', '0.5256', 4.6316, '1'],
       [10, '−0.0429', '0.466', 5.4323, '1'],
       [11, '0.434', '0.687', 8.2287, '−1.0000'],
       [12, '0.2735', '1.0287', 7.1934, '1'],
       [13, '0.4839', '0.4851', 7.485, '−1.0000'],
       [14, '0.4089', '−0.1267', 5.5019, '−1.0000'],
       [15, '1.4391', '0.1614', 8.5843, '−1.0000'],
       [16, '−0.9115', '−0.1973', 2.1962, '−1.0000'],
       [17, '0.3654', '1.0475', 7.4858, '1'],
       [18, '0.2144', '0.7515', 7.1699, '1'],
       [19, '0.2013', '1.0014', 6.5489, '1'],
       [20, '0.6483', '0.2183', 5.8991, '1'],
       [21, '−0.1147', '0.224

In [19]:
start = 1
Anew = Data1[1:4,1:]
print(Anew)

[['−1.4492' '0.8896' 4.4005 '−1.0000']
 ['2.085' '0.6876' 12.071 '−1.0000']
 ['0.2626' '1.1476' 7.7985 '1']]


In [20]:

  
#Data1 = ', '.join(Data1)
#D = np.fromstring(Data1, dtype = np.float, sep =', ' )
  
# printing final result
#rint ("final array", str(Data1))


ValueError: ignored

In [21]:
pred = Data1[22: , 1:4]
print(pred)

[['−1.0625' '0.6366' 2.4707]
 ['0.5307' '0.1285' 5.6883]
 ['−1.2200' '0.7777' 1.7252]
 ['0.3957' '0.1076' 5.6623]
 ['−0.1013' '0.5989' 7.1812]
 ['2.4482' '0.9455' 11.2095]
 ['2.0149' '0.6192' 10.9263]
 ['0.2012' '0.2611' 5.4631]]


In [22]:
test_output = Data1[:22 , 4]
print(test_output)

['−1.0000' '−1.0000' '−1.0000' '1' '1' '−1.0000' '1' '−1.0000' '1' '1'
 '−1.0000' '1' '−1.0000' '−1.0000' '−1.0000' '−1.0000' '1' '1' '1' '1'
 '−1.0000' '1']


In [23]:
pred_output = Data1[22: , 4]
print(pred_output)

['1' '1' '1' '−1.0000' '−1.0000' '1' '-1' '1']


Now we have testcase , pred value , algorithm , So lets test samples

In [81]:
#import perceptron as Perceptron
p = perceptron(learning_rate = 0.01 , n = 1000)
test1 = np.array([[ -0.6508, 0.1097 ,4.0009],
         [-1.4492,0.8896,4.4005],
         [2.085,0.6876,12.071],
         [0.2626,1.1476,7.7985],
         [0.6418,1.0234,7.0427],
         [0.2569,0.673,8.3265]])
        
       

out = np.array([-1.0000,-1.0000 ,-1.0000,1, 1, -1])
#p.fit( test1 , out)
#print(test1)

p.fit( test1 , out)
#print(test1.shape)
pp = np.array([[-1.4492,0.8896,4.4005],[2.085,0.6876,12.071],[ 0.0121, 0.5256, 4.6316],[ -0.0429, 0.466, 5.4323 ]])
#pp = np.array([1.1155, 0.6043, 7.4446])
p.prediction(pp)

array([-1, -1, -1, -1])

predict

In [82]:
p = perceptron(learning_rate = 0.01 , n = 1000)
test2 = np.array([[ -0.6508, 0.1097 ,4.0009],
         [-1.4492,0.8896,4.4005],
         [2.085,0.6876,12.071],
         [0.2626,1.1476,7.7985],
         [0.6418,1.0234,7.0427],
         [0.2569,0.673,8.3265],
         [1.1155, 0.6043, 7.4446,],
         [0.0914, 0.3399, 7.0677],
       [ 0.0121, 0.5256, 4.6316],
       [ -0.0429, 0.466, 5.4323 ],
       [0.434, 0.687, 8.2287],
       [0.2735, 1.0287, 7.1934],
       [0.4839, 0.4851, 7.485],
       [0.4089, -0.1267, 5.5019],
       [1.4391, 0.1614, 8.5843],
       [-0.9115, -0.1973, 2.1962],
       [0.3654, 1.0475, 7.4858],
       [0.2144, 0.7515, 7.1699],
       [0.2013, 1.0014, 6.5489],
       [0.6483, 0.2183, 5.8991],
       [-0.1147, 0.2242, 7.2435],
       [-0.7970, 0.8795, 3.8762,]])
#  [-1.0625, 0.6366, 2.4707],
#        [0.5307, 0.1285, 5.6883],
#        [-1.2200, 0.7777, 1.7252],
#        [0.3957, 0.1076, 5.6623],
#        [-0.1013, 0.5989, 7.1812],
#        [2.4482, 0.9455, 11.2095],
#        [2.0149, 0.6192, 10.9263,],
#        [0.2012, 0.2611, 5.4631]])

      
out2 = [-1.0000,-1.0000 ,-1.0000,1, 1, -1.0000, 1, 1.0000, 1, 1,
 -1.0000 ,1 ,-1.0000 ,-1.0000 ,-1.0000 ,-1.0000, 1 ,1 ,1 ,1 ,-1.0000 ,1]

p.fit(test2 ,out2)

pp2 =np.array( [[-1.0625, 0.6366, 2.4707],[0.5307, 0.1285, 5.6883], [-1.2200, 0.7777, 1.7252],[0.3957, 0.1076, 5.6623], [-0.1013, 0.5989, 7.1812],[2.4482, 0.9455, 11.2095],[2.0149, 0.6192, 10.9263,], [0.2012, 0.2611, 5.4631]])
p.prediction(pp2)


array([ 1,  1,  1,  1, -1,  1,  1,  1])